version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: familychef
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    # Removed volumes section for production optimization
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DEBUG=1
      - SECRET_KEY=dev-secret-key-for-docker-compose-only
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/familychef
      - REDIS_URL=redis://redis:6379/0

  celery:
    build: .
    command: celery -A familychef worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DEBUG=1
      - SECRET_KEY=dev-secret-key-for-docker-compose-only
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/familychef
      - REDIS_URL=redis://redis:6379/0

  celery-beat:
    build: .
    command: celery -A familychef beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DEBUG=1
      - SECRET_KEY=dev-secret-key-for-docker-compose-only
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/familychef
      - REDIS_URL=redis://redis:6379/0

volumes:
  postgres_data:
  redis_data: