# Generated by Django 5.0.14 on 2025-06-16 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_order_orderitemingredient"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("alert_type", models.CharField(choices=[("LOW_STOCK", "Low Stock"), ("EXPIRED", "Expired")], max_length=20)),
                ("message", models.TextField()),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("family", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.family")),
                ("ingredient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.ingredient")),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["family", "is_resolved"], name="core_alert_family__43d598_idx"),
                    models.Index(fields=["alert_type", "is_resolved"], name="core_alert_alert_t_7c90f6_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="LowStockThreshold",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("threshold_qty", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("family", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.family")),
                ("ingredient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.ingredient")),
            ],
            options={
                "unique_together": {("family", "ingredient")},
            },
        ),
    ]
