# Generated by Django 5.0.14 on 2025-06-16 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alert_lowstockthreshold"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppingList",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("qty_needed", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("family", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.family")),
                ("ingredient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.ingredient")),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["family", "resolved_at"], name="core_shoppi_family__3f3c33_idx")],
                "unique_together": {("family", "ingredient")},
            },
        ),
    ]
